version: "3.9"
services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring

  user-db:
    image: postgres:16
    restart: always
    container_name: user-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - spring
    volumes:
      - users_pgdata:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    restart: always
    container_name: order-db
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - spring
    volumes:
      - orders_pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - discovery-service
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/users
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - spring

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - discovery-service
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - spring

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - discovery-service
      - user-service
      - order-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - spring

networks:
  spring:
    driver: bridge

volumes:
  users_pgdata:
  orders_pgdata: